### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by b-schubert** [KohlbacherLab/fred#10]
- Pymmune
- ImmuPy
- Pydaptive
- ePYtope
- scikit-immuno
- PyTope

**Comment by christopher-mohr** [comment]
I would vote for `Pymmune` and `PyTope` 👍.

**Comment by lkuchenb** [comment]
Another voter: `epytope`

**Comment by lkuchenb** [comment]
Another voter: `immupy` or `epytope`

**Comment by b-schubert** [comment]
+2 ePytope
+1 Pymmune

**Comment by christopher-mohr** [comment]
Conducted an additional poll at QBiC ;)

```
ePYtope   |  55% (6)
ImmuPy   |  27% (3)
scikit-immuno  |  9% (1)
PyTope   |  9% (1)

```

**Comment by lkuchenb** [comment]
epytope it is 👍
